### ISSUE TITLE
Rotate Extension Error

### ISSUE THREAD

**Issue by dsssssssss9** [bsiever/microbit-pxt-rotate#1]
Hello

When I tried your example for the New rotate extension i get the following errors...

When i 1st click download i get....

![image](https://user-images.githubusercontent.com/30810847/195170657-427e469a-f7d7-443b-9357-dccb087fbe7a.png)

subsequent click of the download button give the following...

![image](https://user-images.githubusercontent.com/30810847/195167792-c51d490e-6684-4305-bd32-1e4ce1e7a243.png)

makecode.microbit.org version:  [5.0.12](

Microsoft MakeCode version:  [8.0.7](

microbit runtime version:  [v2.2.0-rc6]

codal-microbit-v2 runtime version:  [v0.2.40]

Any idea why?

**Comment by bsiever** [comment]
Hi @dsssssssss9  --- the current release (v0.1.5) requires an update to the Micro:bit CODAL version.  It's waiting on this pull request: https://github.com/microsoft/pxt-microbit/pull/4866.  

My previous version, v0.1.3, should work ok, but it was doing pretty ugly hack to work on the micro:bit v2.  (The v2 will abort animations to change directions in v0.1.3  The new v0.1.5 update can change orientation in the middle of an animation)

There are two temporary workarounds you can use:

1. You can use this version of MakeCode, which uses the newer version of CODAL (v0.2.43), which works with the current release of the extension: https://makecode.microbit.org/app/37f6efa929bcadb89d3f5b689c0cf3cae27e49d1-df227f1388 .
2. Or instead, you can use this shared project, which was using the older (hacky v0.1.3) version of the extension: https://makecode.microbit.org/_e1cKTWW8t1fK

**Comment by dsssssssss9** [comment]
Many thanks for the info ....

Will try the 1.3 version until the PR is completed...

**Comment by bsiever** [comment]
Update:  PR is complete, but still waiting for the updated version of MakeCode to be deployed / switch to CODAL >= v0.2.43.
